### PR TITLE
add some ui code

### PR DESCRIPTION
**Pull request by HengzheLi**
Hope to be able to contribute some help

### CODE REVIEW

**Review by dingmaotu — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution! UI part of this lib is still in its early stage and needs a lot of work.

Here may I propose some changes before this commit be merged:

1. I see you are using visual studio, but no need to include VS specific files (like `.vs` directory). Better add these to `.gitignore` and remove them from this commit

2. In UIElement.mqh, there is no need to delete parent as parents delete their children. It's how the UI hierarchy works.

Other code is great. After these changes, the request will be merged.

**Comment by HengzheLi** [comment]
glad to see your comments.

For your #2 comment, in my c++ knowledge, I think it is better to delete the pointer which the class declares in the class's destructor. It only deletes the local pointer and there is no affection to the original variant which the pointer points to.

And from my experience, every pointer which are not deleted when the class is removed will cause the memory leaking. This may can be see in the log of EA tab under MT4 client.

**Comment by dingmaotu** [comment]
Hi, thanks for the code.

About the pointer thing: it is better to distinguish between pointers and references: the former is what you create, which **YOU** have to delete in the destructor (because you own the resource, others will not delete it for you); while the later is just a reference to an object that others create, be it created by some other class (deleted in **THAT** class's destructor) or simply a GetPointer from a local stack allocated object. Basically, you delete what you created in your constructor (owned by you).

Certainly there are situations where the ownership can be transferred. For example, for the collections class, you **new**ed an object and add it to a collection. Generally you want the collection class to delete it for you. You will not delete an object twice because it is an error. But if you use `SafeDelete` function, you can delete a pointer many times without error, but it is not recommended. See `Lang/Pointer.mqh` for more information.

For the UI hierarchy, a top level object will be allocated on the stack or deleted by the main method. It will delete all its children. So its children only **REFERENCES** their parent, but not **OWNED** them, so no need to delete them. This works like the C++ Qt library. You can see the Qt memory management documentation for detailed explanation.

Read the following code: `UIRoot` object `root` will delete everything because every UI element is its child. There is no leak.

```MQL5
#include <Mql/Trade/Account.mqh>
#include <Mql/Trade/FxSymbol.mqh>
#include <Mql/UI/FreeFormElement.mqh>

string PrintTickInfo(const FxSymbol &s)
  {
   return StringFormat("Info of %s\n"
                       "TickSize: %f\n"
                       "TickValue: %f\n"
                       "Point: %d\n"
                       "Long Swap: %f\n"
                       "Short Swap: %f\n"
                       "Initial Margin: %f\n"
                       "Maintenance Margin: %f",
                       s.getName(),
                       s.getTickSize(),
                       s.getTickValue(),
                       s.getPoint(),
                       s.getLongSwap(),
                       s.getShortSwap(),
                       s.getInitialMargin(),
                       s.getMaintenanceMargin());
  }
//+------------------------------------------------------------------+
//| Script program start function                                    |
//+------------------------------------------------------------------+
void OnStart()
  {
   UIRoot root(0,1);

   Panel *panel=new Panel(GetPointer(root),"toplevel",0,0,100,100);
   root.add(panel);

   FxSymbol sg("GOLD");
   Button *gold=new Button(panel,"gold",PrintTickInfo(sg));
   gold.setPosition(0, 0);
   gold.setSize(100, 50);
   panel.add(gold);

   FxSymbol suj("USDJPY");
   Button *usdjpy=new Button(panel,"usdjpy",PrintTickInfo(suj));
   usdjpy.setPosition(0, gold.getY()+50);
   usdjpy.setSize(100, 50);
   panel.add(usdjpy);

   root.redraw();

   Sleep(5000);
  }
```

**Comment by HengzheLi** [comment]
Got that. 
Thanks for your patient explanation

**Pull request closed without merging**
